FROM node:lts-alpine3.19

WORKDIR /app/server

COPY ui/package.json ./package.json
COPY ui/package-lock.json ./package-lock.json
RUN ls

RUN npm install 
COPY . ./
RUN ls
WORKDIR /app/server/ui
RUN npm run build

RUN ls

EXPOSE 3000 

CMD npm start
