FROM node:lts-alpine3.19

WORKDIR /app/server

COPY frontend/package.json ./package.json
COPY frontend/package-lock.json ./package-lock.json
RUN ls

RUN npm install 
COPY . ./
RUN ls
WORKDIR /app/server/frontend
RUN npm run build

RUN ls

EXPOSE 3000 

CMD npm start
