name: Build and Deploy to VM

on:
  workflow_dispatch:

jobs:
  build-api-server:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v3

      - name: 'Build API Server Container'
        run: |
          docker build -t "ghcr.io/${{secrets.GH_USER}}/api-server" \
                       -f pipeline/Dockerfile .

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Push API Server Container'
        run: docker push "ghcr.io/${{secrets.GH_USER}}/api-server"

  deploy-api-server:
    needs: build-api-server
    runs-on: ubuntu-latest

    steps:
      - name: 'Deploy API Server Container'
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          script: |
            pwd
            ls -l
